### ISSUE TITLE
extractContigs

### ISSUE THREAD

**Issue by Strapagiel** [BiobankLab/FA_TOOL#1]
extractContigs

lista ma nazwy 9 contigów, wynik to 8 contigów
blul@blul-Z97-HD3:~/BIOIT/FA_TOOL$ python fatool.py -f /media/blul/NSEQ/FASTQ/Genomy/Bakterie/Mkansasii/SPADES/Zlozenia/2aJD_run/CONTIGuator_results/UnMappedContigs/NoCoverage.fsa extractContigs --list /media/blul/NSEQ/FASTQ/Genomy/Bakterie/Mkansasii/SPADES/Zlozenia/2aJD_run/CONTIGuator_results/UnMappedContigs/doRAST.txt -o /media/blul/NSEQ/FASTQ/Genomy/Bakterie/Mkansasii/SPADES/Zlozenia/2aJD_run/CONTIGuator_results/UnMappedContigs/doRAST_contigs.fsa
extracting contigs
list items: 9; extracted contigs: 8
Sprawdzone, jest 9, dodatkowo, jak dorzuciłem enter na koniec w doRAST.txt to:
list items: 10; extracted contigs: 8

**Comment by blazejmarciniak** [comment]
prześlesz mi oba pliki,

na chwilę obecną pusta linia też jest traktowana jako nazwa contiga

2016-04-07 12:56 GMT+02:00 Strapagiel notifications@github.com:

**Comment by Strapagiel** [comment]
[NoCoverage.txt](https://github.com/BiobankLab/FA_TOOL/files/208425/NoCoverage.txt)

OK, dla kolejnego pliku ta sama sytuacja, ale jak juæ pracujemy na duæym zestawieniu (z kilkuset zachowaj 20, to dziala ok).
Pliki problematyczne w zalaczeniu
[doRAST.txt](https://github.com/BiobankLab/FA_TOOL/files/208418/doRAST.txt)
[NoCoverage.txt](https://github.com/BiobankLab/FA_TOOL/files/208426/NoCoverage.txt)
w pliku no coverage zmien rozszerzenie na fsa

**Comment by blazejmarciniak** [comment]
Poprawione (jeśli działa zamknij)
